version: '2'
services:
  mysql:
    image: mysql:latest
    container_name: mysql_webflux
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: flux_db
      MYSQL_ROOT_HOST: '%'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --default-time-zone=UTC
    ports:
      - '3306:3306'
    volumes:
      - mysql:/var/lib/mysql

#  hibernate:
#    depends_on:
#      - mysql
#    container_name: hibernate
#    build:
#      dockerfile: Dockerfile
#    image: sb_hibernate:latest
#    ports:
#      - '8083:8083'
#    environment:
#      SPRING_PROFILES_ACTIVE: Hibernate, docker
#    networks:
#      - spring-cloud-network
#networks:
#  spring-cloud-network:
#    driver: bridge
volumes:
  mysql:
    driver: local
