services:
  mysql:
    image: mysql:latest
    container_name: mysql_webflux
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: flux_db
      MYSQL_ROOT_HOST: '%'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --default-time-zone=UTC
    ports:
      - '3306:3306'
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - common-network
  mongo:
    image: mongo:latest
    container_name: mongo_webflux
    restart: always
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
  server_webflux:
    depends_on:
      - mysql
    container_name: server_webflux
    build:
      dockerfile: Dockerfile
    image: server_webflux:latest
    ports:
      - '8081:8081'
    environment:
      SPRING_PROFILES_ACTIVE: route, docker
    networks:
      - common-network
volumes:
  mysql:
    driver: local
networks:
  common-network:
    driver: bridge